services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gilacommerce'
      - 'POSTGRES_PASSWORD=gilacommerce_dev_pw'
      - 'POSTGRES_USER=gila_app'
    ports:
      - '5432:5432'
    volumes:
      - gila_dev_postgres_data:/var/lib/postgresql

volumes:
  gila_dev_postgres_data:
