CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE product (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         VARCHAR(64) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    category    VARCHAR(100),
    price       NUMERIC(12, 2) NOT NULL,
    stock       INT NOT NULL,
    weight_kg   NUMERIC(10, 3),
    version     BIGINT NOT NULL DEFAULT 0,
    deleted_at  TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_product_sku ON product (sku) WHERE deleted_at IS NULL;

CREATE INDEX idx_product_name_trgm ON product USING GIN (name gin_trgm_ops);

CREATE TABLE import_job (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name      VARCHAR(255) NOT NULL,
    executed_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_rows     INT NOT NULL,
    success_count  INT NOT NULL,
    failure_count  INT NOT NULL,
    status         VARCHAR(32) NOT NULL
);

CREATE TABLE import_job_error (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_job_id BIGINT NOT NULL,
    row_number    INT NOT NULL,
    raw_data      TEXT,
    error_reason  VARCHAR(500) NOT NULL,
    CONSTRAINT fk_import_job_error_job FOREIGN KEY (import_job_id) REFERENCES import_job (id)
);

CREATE TABLE cart (
    id         UUID PRIMARY KEY,
    status     VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    UUID NOT NULL,
    product_id BIGINT NOT NULL,
    quantity   INT NOT NULL,
    added_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id) REFERENCES cart (id),
    CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT uq_cart_item_cart_product UNIQUE (cart_id, product_id)
);

CREATE TABLE orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    UUID,
    status     VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_cart FOREIGN KEY (cart_id) REFERENCES cart (id)
);

CREATE TABLE order_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT NOT NULL,
    product_id          BIGINT NOT NULL,
    name                VARCHAR(255) NOT NULL,
    price_at_purchase   NUMERIC(12, 2) NOT NULL,
    version_at_purchase BIGINT NOT NULL,
    quantity            INT NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE INDEX idx_order_item_order_id ON order_item (order_id);
