CREATE TABLE product_audit (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NOT NULL,
    action        VARCHAR(32) NOT NULL,
    import_job_id BIGINT,
    sku           VARCHAR(64) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    category      VARCHAR(100),
    price         NUMERIC(12, 2) NOT NULL,
    weight_kg     NUMERIC(10, 3),
    version       BIGINT NOT NULL,
    recorded_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_audit_product FOREIGN KEY (product_id) REFERENCES product (id),
    CONSTRAINT fk_product_audit_import_job FOREIGN KEY (import_job_id) REFERENCES import_job (id)
);

CREATE INDEX idx_product_audit_product_id ON product_audit (product_id);
