spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gilacommerce}
    username: ${SPRING_DATASOURCE_USERNAME:gila_app}
    password: ${SPRING_DATASOURCE_PASSWORD:gilacommerce_dev_pw}
